version: 2
updates:
  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'type:chore'
    groups:
      gradle-minor:
        update-types: ['minor', 'patch']

  - package-ecosystem: 'npm'
    directories:
      - '/apps/pos-terminal'
      - '/apps/admin-dashboard'
      - '/packages/shared-types'
      - '/e2e'
    schedule:
      interval: 'weekly'
    labels:
      - 'type:chore'
    groups:
      npm-monorepo-minor:
        patterns: ['*']
        group-by: dependency-name
        update-types: ['minor', 'patch']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'type:chore'
    groups:
      actions-minor:
        update-types: ['minor', 'patch']
