version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type:chore"

  - package-ecosystem: "npm"
    directory: "/apps/pos-terminal"
    schedule:
      interval: "weekly"
    labels:
      - "type:chore"

  - package-ecosystem: "npm"
    directory: "/apps/admin-dashboard"
    schedule:
      interval: "weekly"
    labels:
      - "type:chore"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type:chore"

  - package-ecosystem: "npm"
    directory: "/packages/shared-types"
    schedule:
      interval: "weekly"
    labels:
      - "type:chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type:chore"
